name = "InteractBase"
uuid = "d3863d7c-f0c8-5437-a7b4-3ae773c01009"
version = "0.10.3"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
CSSUtil = "70588ee8-6100-5070-97c1-3cb50ed05fe8"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JSExpr = "97c1335a-c9c5-57fe-bc5d-ec35cebe8660"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Knockout = "bcebb21b-c2e3-54f8-a781-646b90f6d2cc"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
WebIO = "0f1e0344-ec1d-5b48-a673-e5cf874b6c29"
Widgets = "cc8bc4a8-27d6-5769-a93b-9d913e69aa62"

[compat]
julia = "0.7, 1"
JSExpr = "≥ 0.3.0"
Knockout = "≥ 0.2.1"
Observables = "≥ 0.2.2"
WebIO = "≥ 0.3.0"
Widgets = "≥ 0.6.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
